language: cpp
before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install g++-5 -y
  - sudo rm -f /usr/bin/gcc
  - sudo rm -f /usr/bin/g++
  - sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - g++ -v
branches:
  except:
    - gh-pages
env:
  global:
    - GH_REPO_NAME: otuscpp_04_print_ip
    - GH_REPO_REF: github.com/flanker-d/otuscpp_04_print_ip.git
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      - libboost-test-dev
script:
  - pwd
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
compiler: g++
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uflanker-d:$BINTRAY_API_KEY "https://api.bintray.com/content/flankerd/otuscpp/04_print_ip/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x deploy_documentation.sh
  - ./deploy_documentation.sh
  
