language: cpp
branches:
  except:
    - gh-pages
env:
  global:
    - GH_REPO_NAME: otuscpp_04_print_ip
    - GH_REPO_REF: github.com/flanker-d/otuscpp_04_print_ip.git
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      - libboost-test-dev
      - g++-5
script:
  - pwd
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
compiler: g++
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uflanker-d:$BINTRAY_API_KEY "https://api.bintray.com/content/flankerd/otuscpp/04_print_ip/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x deploy_documentation.sh
  - ./deploy_documentation.sh
  
